<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_DumpsMechanicalEng extends Dase_DBO 
{
	public function __construct($db,$assoc = false) 
	{
		parent::__construct($db,'dumps_mechanical_eng', array('title','url','journal','author','userid','fiscal_year','lastupdated','real_name','volume','online_only','pages','author_url','year','_id','details','is_topn','issue','notes','eid'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}