<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_DumpsBusPub extends Dase_DBO 
{
	public function __construct($db,$assoc = false) 
	{
		parent::__construct($db,'dumps_bus_pub', array('eid_count','start_year','title','url','end_year','pubId','publisher','pubTypeID','volume','state','journal_title','editor','edited_volume','pubHTML','forthcoming','issue','pages','representative','pubType','author_order','author','first_name','last_name','middle_name','eid','pubString'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}