<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_UploadedFile extends Dase_DBO 
{
	public function __construct($db,$assoc = false) 
	{
		parent::__construct($db,'uploaded_file', array('name','orig_name','eid','uploaded','upload_mime','uploaded_by','date_on_cv','status','note','rawtext','rawtext_size','rawtext_md5','converted','workflow_state'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}